export interface UniversityData {
  name: string;
  courses: string[];
}

const commonCourses = [
  "BSc Computer Science",
  "BSc Mathematics",
  "BA English Literature",
  "BSc Physics",
  "BSc Chemistry",
  "BSc Biology",
  "BA History",
  "BA Philosophy",
  "BSc Psychology",
  "BA Economics",
  "LLB Law",
  "BSc Nursing",
  "BEng Mechanical Engineering",
  "BEng Civil Engineering",
  "BEng Electrical Engineering",
  "BA Business Management",
  "BSc Accounting and Finance",
  "BA International Relations",
  "BA Politics",
  "BSc Biomedical Science",
  "BA Sociology",
  "BA Criminology",
  "BA Education",
  "BSc Environmental Science",
  "BA Geography",
  "BSc Sports Science",
  "BA Media and Communications",
  "BFA Fine Art",
  "BA Architecture",
  "BSc Data Science",
  "BSc Artificial Intelligence",
  "BSc Cyber Security",
  "BSc Software Engineering",
  "BA Graphic Design",
  "BSc Pharmacy",
  "BDS Dentistry",
  "MBBS Medicine",
  "BSc Neuroscience",
  "BA Music",
  "BA Film Studies",
  "BA Journalism",
  "BSc Forensic Science",
  "BSc Biochemistry",
  "BA Anthropology",
  "BA Linguistics",
  "BSc Genetics",
  "BA Creative Writing",
  "BSc Physiotherapy",
  "BSc Dietetics",
  "BSc Occupational Therapy",
  "BEng Aerospace Engineering",
  "BEng Chemical Engineering",
  "BSc Marine Biology",
  "BA Theology",
  "BSc Zoology",
  "BA Drama and Theatre",
  "BSc Mathematics and Statistics",
  "BA Social Work",
  "BSc Quantity Surveying",
  "BA Fashion Design",
  "MEng Computer Science",
  "MEng Mechanical Engineering",
  "MSci Physics",
  "MSci Chemistry",
  "MChem Chemistry",
  "MMath Mathematics",
];

export const UK_UNIVERSITIES: UniversityData[] = [
  { name: "University of Aberdeen", courses: commonCourses },
  { name: "Aberystwyth University", courses: commonCourses },
  { name: "Anglia Ruskin University", courses: commonCourses },
  { name: "Aston University", courses: commonCourses },
  { name: "Bangor University", courses: commonCourses },
  { name: "University of Bath", courses: commonCourses },
  { name: "Bath Spa University", courses: commonCourses },
  { name: "University of Bedfordshire", courses: commonCourses },
  { name: "Birkbeck, University of London", courses: commonCourses },
  { name: "University of Birmingham", courses: commonCourses },
  { name: "Birmingham City University", courses: commonCourses },
  { name: "University of Bolton", courses: commonCourses },
  { name: "Bournemouth University", courses: commonCourses },
  { name: "University of Bradford", courses: commonCourses },
  { name: "University of Brighton", courses: commonCourses },
  { name: "University of Bristol", courses: commonCourses },
  { name: "Brunel University London", courses: commonCourses },
  { name: "University of Buckingham", courses: commonCourses },
  { name: "Buckinghamshire New University", courses: commonCourses },
  { name: "University of Cambridge", courses: commonCourses },
  { name: "Canterbury Christ Church University", courses: commonCourses },
  { name: "Cardiff University", courses: commonCourses },
  { name: "Cardiff Metropolitan University", courses: commonCourses },
  { name: "University of Central Lancashire", courses: commonCourses },
  { name: "University of Chester", courses: commonCourses },
  { name: "University of Chichester", courses: commonCourses },
  { name: "City, University of London", courses: commonCourses },
  { name: "Coventry University", courses: commonCourses },
  { name: "Cranfield University", courses: commonCourses },
  { name: "De Montfort University", courses: commonCourses },
  { name: "University of Derby", courses: commonCourses },
  { name: "University of Dundee", courses: commonCourses },
  { name: "Durham University", courses: commonCourses },
  { name: "University of East Anglia", courses: commonCourses },
  { name: "University of East London", courses: commonCourses },
  { name: "Edge Hill University", courses: commonCourses },
  { name: "University of Edinburgh", courses: commonCourses },
  { name: "Edinburgh Napier University", courses: commonCourses },
  { name: "University of Essex", courses: commonCourses },
  { name: "University of Exeter", courses: commonCourses },
  { name: "Falmouth University", courses: commonCourses },
  { name: "University of Glasgow", courses: commonCourses },
  { name: "Glasgow Caledonian University", courses: commonCourses },
  { name: "University of Gloucestershire", courses: commonCourses },
  { name: "Goldsmiths, University of London", courses: commonCourses },
  { name: "University of Greenwich", courses: commonCourses },
  { name: "Harper Adams University", courses: commonCourses },
  { name: "Heriot-Watt University", courses: commonCourses },
  { name: "University of Hertfordshire", courses: commonCourses },
  { name: "University of the Highlands and Islands", courses: commonCourses },
  { name: "University of Huddersfield", courses: commonCourses },
  { name: "University of Hull", courses: commonCourses },
  { name: "Imperial College London", courses: commonCourses },
  { name: "Keele University", courses: commonCourses },
  { name: "University of Kent", courses: commonCourses },
  { name: "Kingston University", courses: commonCourses },
  { name: "King's College London", courses: commonCourses },
  { name: "Lancaster University", courses: commonCourses },
  { name: "University of Leeds", courses: commonCourses },
  { name: "Leeds Beckett University", courses: commonCourses },
  { name: "University of Leicester", courses: commonCourses },
  { name: "University of Lincoln", courses: commonCourses },
  { name: "University of Liverpool", courses: commonCourses },
  { name: "Liverpool John Moores University", courses: commonCourses },
  { name: "University of London", courses: commonCourses },
  { name: "London Metropolitan University", courses: commonCourses },
  { name: "London South Bank University", courses: commonCourses },
  { name: "London School of Economics (LSE)", courses: commonCourses },
  { name: "Loughborough University", courses: commonCourses },
  { name: "University of Manchester", courses: commonCourses },
  { name: "Manchester Metropolitan University", courses: commonCourses },
  { name: "Middlesex University", courses: commonCourses },
  { name: "Newcastle University", courses: commonCourses },
  { name: "Northumbria University", courses: commonCourses },
  { name: "University of Northampton", courses: commonCourses },
  { name: "Norwich University of the Arts", courses: commonCourses },
  { name: "University of Nottingham", courses: commonCourses },
  { name: "Nottingham Trent University", courses: commonCourses },
  { name: "Open University", courses: commonCourses },
  { name: "University of Oxford", courses: commonCourses },
  { name: "Oxford Brookes University", courses: commonCourses },
  { name: "University of Plymouth", courses: commonCourses },
  { name: "University of Portsmouth", courses: commonCourses },
  { name: "Queen Margaret University", courses: commonCourses },
  { name: "Queen Mary University of London", courses: commonCourses },
  { name: "Queen's University Belfast", courses: commonCourses },
  { name: "University of Reading", courses: commonCourses },
  { name: "Robert Gordon University", courses: commonCourses },
  { name: "Roehampton University", courses: commonCourses },
  { name: "Royal Holloway, University of London", courses: commonCourses },
  { name: "University of Salford", courses: commonCourses },
  { name: "University of Sheffield", courses: commonCourses },
  { name: "Sheffield Hallam University", courses: commonCourses },
  { name: "SOAS University of London", courses: commonCourses },
  { name: "University of Southampton", courses: commonCourses },
  { name: "University of South Wales", courses: commonCourses },
  { name: "Staffordshire University", courses: commonCourses },
  { name: "University of St Andrews", courses: commonCourses },
  { name: "University of Stirling", courses: commonCourses },
  { name: "University of Strathclyde", courses: commonCourses },
  { name: "University of Suffolk", courses: commonCourses },
  { name: "University of Sunderland", courses: commonCourses },
  { name: "University of Surrey", courses: commonCourses },
  { name: "University of Sussex", courses: commonCourses },
  { name: "Swansea University", courses: commonCourses },
  { name: "Teesside University", courses: commonCourses },
  { name: "University College London (UCL)", courses: commonCourses },
  { name: "Ulster University", courses: commonCourses },
  { name: "University of the West of England (UWE)", courses: commonCourses },
  { name: "University of the West of Scotland", courses: commonCourses },
  { name: "University of Warwick", courses: commonCourses },
  { name: "University of Westminster", courses: commonCourses },
  { name: "University of Winchester", courses: commonCourses },
  { name: "University of Wolverhampton", courses: commonCourses },
  { name: "University of Worcester", courses: commonCourses },
  { name: "University of York", courses: commonCourses },
  { name: "York St John University", courses: commonCourses },
  { name: "London School of Economics (LSE)", courses: commonCourses },
  { name: "Royal Academy of Music", courses: commonCourses },
  { name: "Royal College of Art", courses: commonCourses },
  { name: "University of the Arts London", courses: commonCourses },
  { name: "Arts University Bournemouth", courses: commonCourses },
  { name: "University for the Creative Arts", courses: commonCourses },
  { name: "Liverpool Hope University", courses: commonCourses },
  { name: "Solent University", courses: commonCourses },
  { name: "University of Cumbria", courses: commonCourses },
  { name: "St Mary's University, Twickenham", courses: commonCourses },
  { name: "Ravensbourne University London", courses: commonCourses },
  { name: "Wrexham University", courses: commonCourses },
];

export function searchUniversities(query: string): string[] {
  const q = query.toLowerCase().trim();
  if (!q) return UK_UNIVERSITIES.map((u) => u.name).slice(0, 20);
  return UK_UNIVERSITIES.filter((u) => u.name.toLowerCase().includes(q)).map(
    (u) => u.name,
  );
}

export function getCoursesForUniversity(universityName: string): string[] {
  const uni = UK_UNIVERSITIES.find(
    (u) => u.name.toLowerCase() === universityName.toLowerCase(),
  );
  return uni ? uni.courses : commonCourses;
}

export function searchCourses(
  universityName: string,
  query: string,
): string[] {
  const courses = getCoursesForUniversity(universityName);
  const q = query.toLowerCase().trim();
  if (!q) return courses.slice(0, 20);
  return courses.filter((c) => c.toLowerCase().includes(q));
}
